 - hosts: webservers

   tasks:
     - name: install nginx
       ansible.builtin.apt:
         name: nginx
         state: latest
       become: yes
       tags: nginx

     - name: copy html file
       ansible.builtin.copy:
         src: files/helloWorld/index.html
         dest: /usr/share/nginx/html/index.html
       become: yes

     - name: update nginx config
       ansible.builtin.copy:
         src: files/helloWorld/nginx.conf
         dest: /etc/nginx/nginx.conf
       notify: 
         - restart nginx
       become: yes
       tags: nginx

   handlers:
     - name: restart nginx
       ansible.builtin.service:
         name: nginx
         state: reloaded
       become: yes
