 - hosts: webservers
   gather_facts: no
   vars:
     root_dir: /var/tmp/www
     nginx_port: 8080     
   tasks:
     - name: install nginx
       ansible.builtin.apt:
         name: nginx
         state: latest
       become: yes
       tags: nginx

     - name: create root dir
       ansible.builtin.file:
         path: "{{ root_dir }}"
         state: directory
       become: yes

     - name: copy html file
       ansible.builtin.template:
         src: files/helloWorld/index.html.j2
         dest: "{{ root_dir }}/index.html"
       become: yes

     - name: update nginx config
       ansible.builtin.template:
         src: files/helloWorld/nginx.conf.j2
         dest: "/etc/nginx/nginx.conf"
       notify: 
         - restart nginx
       become: yes
       tags: nginx

   handlers:
     - name: restart nginx
       ansible.builtin.service:
         name: nginx
         state: reloaded
       become: yes
