 - hosts: webservers
   tasks:
     - name: install redis-server
       ansible.builtin.apt: 
         name: redis-server
         state: present
       become: yes

     - name: install git
       ansible.builtin.apt:
         name: git
         state: present
       become: yes
       tags: git

     - name: update cache
       ansible.builtin.apt:
         update-cache: yes
       become: yes
       tags: cache
