 - hosts: webservers

   tasks: 
     - name: remove redis server
       apt: name=redis-server state=absent
       become: yes

     - name: remove git
       apt: name=git state=absent
       become: yes
