 - hosts: webservers
   vars:
     username: grevcev

   tasks: 
     - name: install git on ubuntu
       ansible.builtin.apt:
         name: git
         state: present
       when: ansible_os_family == "Debian"
       become: yes

     - name: install git on centos
       ansible.builtin.yum:
         name: git
         state: present
       when: ansible_os_family == "RedHat"
       become: yes


     - name: copy git config file
       ansible.builtin.template:
         src: "files/.gitconfig.j2"
         dest: "/home/{{ username }}/.gitconfig"
       become: yes
