 - hosts: webservers
   vars:
     text: "This is server: {{ server_name }}"
   tasks:
     - name: install cowsay
       ansible.builtin.apt:
         name: cowsay
         state: latest
       become: true

     - name: generate message from cow
       ansible.builtin.shell: cowsay "Hello, from web server!"
       register: cowsay_result
       become: true

     - name: install nginx
       ansible.builtin.apt:
         name: nginx
         state: latest
       become: yes

     - name: copy html file
       ansible.builtin.template:
         src: files/nginxServer/index.html.j2
         dest: "/var/www/html/index.html"
       become: yes
